In [130]:
import numpy as np
import pandas as pd

In [ ]:
content_df=pd.read_csv("data/telecom_churn_copy.csv")

In [132]:
content_df.head()

,Content ID,Content Type,Genre,Time of Day,Day of the Week,Duration (mins),Viewership,Average Watch Time (mins),Peak Viewership Time,Peak Viewership Day,...,Seasonality,Content Popularity,Competitor Content,Promotion Data,Subscription Data,Merged,Hour,Minute,Hour.1_peak_viewership_time,Minute.1_peak_viewership_time
0,1,Movie,Thriller,23:57:00,Thursday,121,8203,72,10:17:00,Friday,...,Fall,Low,Similar Doc C,Social Media,8883,03-07-2024,23,57,10,17
1,2,Series,Comedy,20:57:00,Friday,1200,64148,115,15:25:00,Saturday,...,Spring,Low,Similar Series B,Print Media,3850,08-09-2024,20,57,15,25
2,3,Movie,Sci-Fi,23:25:00,Friday,170,8216,43,08:50:00,Sunday,...,Fall,Medium,Similar Thriller H,Email Campaign,7835,07-09-2024,23,25,8,50
3,4,Series,Romance,06:59:00,Friday,506,52848,87,14:57:00,Friday,...,Winter,Medium,Similar History G,Online Ads,17506,15-07-2024,6,59,14,57
4,5,Documentary,Fantasy,18:27:00,Sunday,77,14090,42,03:40:00,Saturday,...,Winter,Low,Similar Movie A,30% off,8675,05-07-2024,18,27,3,40

In [133]:
content_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 27 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Content ID                     1000 non-null   int64
 1   Content Type                   1000 non-null   object
 2   Genre                          1000 non-null   object
 3   Time of Day                    1000 non-null   object
 4   Day of the Week                1000 non-null   object
 5   Duration (mins)                1000 non-null   int64
 6   Viewership                     1000 non-null   int64
 7   Average Watch Time (mins)      1000 non-null   int64
 8   Peak Viewership Time           1000 non-null   object
 9   Peak Viewership Day            1000 non-null   object
 10  Viewer Age                     1000 non-null   object
 11  Viewer Gender                  1000 non-null   object
 12  Viewer Location                1000 non-null   object
 13  Likes                          1000 non-null   int64
 14  Shares                         1000 non-null   int64
 15  Comments                       1000 non-null   int64
 16  User Ratings                   1000 non-null   float64
 17  Seasonality                    1000 non-null   object
 18  Content Popularity             1000 non-null   object
 19  Competitor Content             1000 non-null   object
 20  Promotion Data                 1000 non-null   object
 21  Subscription Data              1000 non-null   int64
 22  Merged                         1000 non-null   object
 23  Hour                           1000 non-null   int64
 24  Minute                         1000 non-null   int64
 25  Hour.1_peak_viewership_time    1000 non-null   int64
 26  Minute.1_peak_viewership_time  1000 non-null   int64
dtypes: float64(1), int64(12), object(14)
memory usage: 211.1+ KB

In [134]:
content_df.isna().sum()

Content ID                       0
Content Type                     0
Genre                            0
Time of Day                      0
Day of the Week                  0
Duration (mins)                  0
Viewership                       0
Average Watch Time (mins)        0
Peak Viewership Time             0
Peak Viewership Day              0
Viewer Age                       0
Viewer Gender                    0
Viewer Location                  0
Likes                            0
Shares                           0
Comments                         0
User Ratings                     0
Seasonality                      0
Content Popularity               0
Competitor Content               0
Promotion Data                   0
Subscription Data                0
Merged                           0
Hour                             0
Minute                           0
Hour.1_peak_viewership_time      0
Minute.1_peak_viewership_time    0
dtype: int64

In [135]:
content_df['Time of Day']=pd.to_datetime(content_df["Time of Day"],dayfirst=True)
content_df['Merged']=pd.to_datetime(content_df["Merged"],dayfirst=True)
content_df["Peak Viewership Time"]=pd.to_datetime(content_df["Peak Viewership Time"],dayfirst=True)

C:\Users\akhil kottakota\AppData\Local\Temp\ipykernel_19776\2861516416.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  content_df['Time of Day']=pd.to_datetime(content_df["Time of Day"],dayfirst=True)
C:\Users\akhil kottakota\AppData\Local\Temp\ipykernel_19776\2861516416.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  content_df["Peak Viewership Time"]=pd.to_datetime(content_df["Peak Viewership Time"],dayfirst=True)

In [136]:
content_df_cont=content_df.select_dtypes(include=["int64","float64"])
content_df_cat=content_df.select_dtypes(include=["object"])

In [137]:
content_encoding=pd.get_dummies(content_df_cat,drop_first=True)
content_encoding=content_encoding.astype('int')

In [138]:
content_new_df=pd.concat([content_df_cont,content_encoding],axis=1)

In [139]:
content_weekend_views=content_df.loc[content_df["Peak Viewership Day"].isin(["Saturday","Sunday"]),:]
content_weekday_views=content_df.loc[content_df["Peak Viewership Day"].isin(["Thursday","Tuesday","Friday","Wednesday","Monday"]),:]

In [140]:
content_A=content_df.loc[content_df["Competitor Content"]=="Similar Movie A",:]
content_B=content_df.loc[content_df["Competitor Content"]=="Similar Series B",:]

In [141]:
content_weekday_released=content_df.loc[content_df["Day of the Week"].isin(["Friday","Tuesday","Thursday","Monday","Wednesday"]),:]
content_weekend_released=content_df.loc[content_df["Day of the Week"].isin(["Saturday","Sunday"]),:]

In [142]:
weekend_thiller_views=content_weekend_views.loc[content_weekend_views["Genre"]=="Thriller",:].reset_index(drop=True)
weekday_thiller_views=content_weekday_views.loc[content_weekday_views["Genre"]=="Thriller",:].reset_index(drop=True)

In [143]:
content_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 27 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Content ID                     1000 non-null   int64
 1   Content Type                   1000 non-null   object
 2   Genre                          1000 non-null   object
 3   Time of Day                    1000 non-null   datetime64[ns]
 4   Day of the Week                1000 non-null   object
 5   Duration (mins)                1000 non-null   int64
 6   Viewership                     1000 non-null   int64
 7   Average Watch Time (mins)      1000 non-null   int64
 8   Peak Viewership Time           1000 non-null   datetime64[ns]
 9   Peak Viewership Day            1000 non-null   object
 10  Viewer Age                     1000 non-null   object
 11  Viewer Gender                  1000 non-null   object
 12  Viewer Location                1000 non-null   object
 13  Likes                          1000 non-null   int64
 14  Shares                         1000 non-null   int64
 15  Comments                       1000 non-null   int64
 16  User Ratings                   1000 non-null   float64
 17  Seasonality                    1000 non-null   object
 18  Content Popularity             1000 non-null   object
 19  Competitor Content             1000 non-null   object
 20  Promotion Data                 1000 non-null   object
 21  Subscription Data              1000 non-null   int64
 22  Merged                         1000 non-null   datetime64[ns]
 23  Hour                           1000 non-null   int64
 24  Minute                         1000 non-null   int64
 25  Hour.1_peak_viewership_time    1000 non-null   int64
 26  Minute.1_peak_viewership_time  1000 non-null   int64
dtypes: datetime64[ns](3), float64(1), int64(12), object(11)
memory usage: 211.1+ KB

In [144]:
content_df["viewership_bins"]=pd.cut(content_df["Viewership"],bins=5)
content_df["Shares_bins"]=pd.cut(content_df["Shares"],bins=5)
content_df["Comments_bins"]=pd.cut(content_df["Comments"],bins=5)
content_df["Likes_bins"]=pd.cut(content_df["Likes"],bins=5)

In [145]:
content_df["viewership_bins"]=content_df["viewership_bins"].astype('str')
content_df["Shares_bins"]=content_df["Shares_bins"].astype('str')
content_df["Comments_bins"]=content_df["Comments_bins"].astype('str')
content_df["Likes_bins"]=content_df["Likes_bins"].astype('str')

In [146]:
content_df["viewership_bins"]=content_df["viewership_bins"].replace({"(-37.907, 20043.4]":1,
                                    "(20043.4, 40024.8]":2,
                                    "(40024.8, 60006.2]":3,
                                       "(60006.2, 79987.6]":4,
                                       "(79987.6, 99969.0]":5})

C:\Users\akhil kottakota\AppData\Local\Temp\ipykernel_19776\2749866951.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  content_df["viewership_bins"]=content_df["viewership_bins"].replace({"(-37.907, 20043.4]":1,

In [147]:
content_df["viewership_bins"]=content_df["viewership_bins"].replace({"(-37.907, 20043.4]":1,
                                    "(20043.4, 40024.8]":2,
                                    "(40024.8, 60006.2]":3,
                                       "(60006.2, 79987.6]":4,
                                       "(79987.6, 99969.0]":5})

In [148]:
content_df["Likes_bins"]=content_df["Likes_bins"].replace({"(8.013, 608.4]":1,
                                    "(608.4, 1205.8]":2,
                                    "(1205.8, 1803.2]":3,
                                       "(1803.2, 2400.6]":4,
                                       "(2400.6, 2998.0]":5})

C:\Users\akhil kottakota\AppData\Local\Temp\ipykernel_19776\3440699089.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  content_df["Likes_bins"]=content_df["Likes_bins"].replace({"(8.013, 608.4]":1,

In [149]:
content_df["Comments_bins"]=content_df["Comments_bins"].replace({"(0.503, 301.4]":1,
                                    "(301.4, 600.8]":2,
                                    "(600.8, 900.2]":3,
                                       "(900.2, 1199.6]":4,
                                       "(1199.6, 1499.0]":5})

C:\Users\akhil kottakota\AppData\Local\Temp\ipykernel_19776\1753193812.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  content_df["Comments_bins"]=content_df["Comments_bins"].replace({"(0.503, 301.4]":1,

In [150]:
content_df["Shares_bins"]=content_df["Shares_bins"].replace({"(2.005, 403.0]":1,
                                    "(403.0, 802.0]":2,
                                    "(802.0, 1201.0]":3,
                                       "(1201.0, 1600.0]":4,
                                       "(1600.0, 1999.0]":5})

C:\Users\akhil kottakota\AppData\Local\Temp\ipykernel_19776\703204097.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  content_df["Shares_bins"]=content_df["Shares_bins"].replace({"(2.005, 403.0]":1,

In [151]:
# What are the top 10 most viewed content pieces overall?
Top_content=content_df.groupby(by=["Content ID"]).agg({"Viewership":"sum"}).reset_index()
Top_content.sort_values(by=["Viewership"],ascending=[False],inplace=True)
Top_content.iloc[0:10,:].reset_index(drop=True)

   Content ID  Viewership
0         960       99969
1         252       99939
2         136       99744
3         989       99660
4         280       99483
5         936       99438
6         441       99427
7         783       99424
8         209       99019
9         213       98861

In [152]:
# What are the most-watched genres in each region?
genre_by_location_views=content_df.groupby(["Viewer Location","Genre"]).agg({"Viewership":"sum"}).reset_index()
genre_by_location_views.sort_values(by=["Viewership","Viewer Location"],ascending=[False,True],inplace=True)
genre_by_location_views=genre_by_location_views.reset_index(drop=True)
genre_by_location_views['genre_rank']=genre_by_location_views.groupby("Viewer Location")["Viewership"].rank(method='min',ascending=False)
genre_by_location_views.loc[genre_by_location_views["genre_rank"]==1.0,:]

   Viewer Location     Genre  Viewership  genre_rank
0            India  Thriller     1222200         1.0
1            Italy     Drama     1208469         1.0
2           Canada  Thriller     1132962         1.0
4          Germany   Romance     1066136         1.0
6               UK    Sci-Fi     1058724         1.0
9        Australia    Action      971383         1.0
18          France    Sci-Fi      830265         1.0
29             USA     Drama      751135         1.0

In [153]:
# Which genre has the highest average watch time?
viewership_by_genre=content_df.groupby(["Genre"]).agg({"Viewership":np.average}).reset_index()
viewership_by_genre=viewership_by_genre.sort_values(by=["Viewership"],ascending=[False]).reset_index(drop=True)
# viewership_by_genre.iloc[[0],:]
viewership_by_genre

      Genre    Viewership
0    Comedy  54616.292929
1    Action  53425.303571
2    Sci-Fi  52367.063636
3    Nature  51512.913043
4  Thriller  51402.503937
5     Drama  51016.339130
6   History  49629.336449
7   Romance  49196.048780
8   Fantasy  48099.878261

In [154]:
# What time of day has the highest viewer engagement?
peak_viewership_by_genre=content_df.groupby(by=["Peak Viewership Time"]).agg({"Viewership":"sum"}).reset_index()
peak_viewership_by_genre=peak_viewership_by_genre.sort_values(by=["Viewership"],ascending=[False]).reset_index(drop=True)
peak_viewership_by_genre.iloc[[0],:]

  Peak Viewership Time  Viewership
0  2026-02-21 02:44:00      403707

In [155]:
# Which days of the week drive the most views?​
views_by_week_day=content_df.groupby(by=["Peak Viewership Day"]).agg({"Viewership":"sum"}).reset_index()
views_by_week_day.iloc[[0],:]

  Peak Viewership Day  Viewership
0              Friday    13604412

In [156]:
# What is the average user rating for different content types (Movies vs Series)?
rating_by_content_type=content_df.groupby(by=["Content Type"]).agg({"User Ratings":np.average}).reset_index()
rating_by_content_type=rating_by_content_type.sort_values(by=["User Ratings"],ascending=[False])
rating_by_content_type.reset_index(drop=True)

  Content Type  User Ratings
0        Movie      2.849853
1  Documentary      2.849390
2       Series      2.730514

In [157]:
#How many likes, shares, and comments are generated per content type?
likes_by_content_type=content_df.groupby(by=["Content Type"]).agg({"Likes":"sum",
                                             "Shares":"sum",
                                             "Comments":"sum"}).reset_index()
likes_by_content_type=likes_by_content_type.sort_values(by=["Likes","Shares","Comments"],ascending=[False,False,False])
likes_by_content_type.reset_index(drop=True)

  Content Type   Likes  Shares  Comments
0        Movie  516023  341087    257194
1       Series  501522  321422    243899
2  Documentary  479880  310595    242023

#Diagnostic Analysis

In [158]:
# Why did the viewership for "Thriller" genre spike on weekends?
thriller_data=content_df.loc[content_df["Genre"]=="Thriller",:]
views_by_weekday=thriller_data.groupby(by=["Peak Viewership Day"]).agg({"Viewership":"sum"}).reset_index()
views_by_weekday.sort_values(by=["Viewership"],ascending=[False]).reset_index(drop=True)

  Peak Viewership Day  Viewership
0            Saturday     2578846
1              Sunday     1663004
2              Friday     1615472
3             Tuesday      670796

In [159]:
views_by_weekdays=content_df.groupby(by=["Peak Viewership Day"]).agg({"Viewership":"sum"}).reset_index()
weekend=views_by_weekdays.loc[views_by_weekdays["Peak Viewership Day"].isin(["Saturday","Sunday"]),:]
weekend["Viewership"].mean()

np.float64(16096969.5)

In [160]:
weekday=views_by_weekdays.loc[views_by_weekdays["Peak Viewership Day"].isin(["Friday","Monday","Thursday","Tuesday","Wednesday"]),:]
weekday["Viewership"].mean()

np.float64(3796841.8)

In [161]:
weekend_thiller_views.groupby(["Peak Viewership Day"]).agg({"Viewership":"sum"}).reset_index()
weekend_thiller_views["Viewership"].sum()

np.int64(4241850)

In [162]:
thriller_data_view=thriller_data.groupby(by=["Viewer Gender"]).agg({"Viewership":"mean"})

In [163]:
thriller_data_by_location=thriller_data.groupby(["Peak Viewership Day","Viewer Location","Viewer Age","Viewer Gender"]).agg({"Viewership":"sum"}).reset_index()
thriller_data_by_location.sort_values(by=["Viewership"],ascending=[False],inplace=True)
thriller_data_by_location.iloc[0:10].reset_index(drop=True)

  Peak Viewership Day Viewer Location Viewer Age Viewer Gender  Viewership
0            Saturday          Canada      35-44          Male      182287
1            Saturday       Australia      25-34          Male      175206
2              Friday              UK      45-54        Female      159467
3              Sunday           India      45-54        Female      154181
4             Tuesday          Canada      18-24          Male      146046
5              Friday           Italy      45-54        Female      145504
6              Sunday              UK      25-34        Female      143924
7              Friday          France      18-24        Female      135018
8              Sunday           Italy      18-24          Male      120702
9            Saturday           India      35-44          Male      112479

In [164]:
weekend_thiller_views=content_weekend_views.loc[content_weekend_views["Genre"]=="Thriller",:].reset_index(drop=True)
weekend_thiller_views=weekend_thiller_views.groupby(["Peak Viewership Day","Viewer Location","Viewer Age","Viewer Gender"]).agg({"Viewership":"sum"}).reset_index()
weekend_thiller_views.sort_values(by=["Viewership"],ascending=[False]).reset_index(drop=True)
# weekend_thiller_views["Viewership"].sum()

   Peak Viewership Day Viewer Location Viewer Age Viewer Gender  Viewership
0             Saturday          Canada      35-44          Male      182287
1             Saturday       Australia      25-34          Male      175206
2               Sunday           India      45-54        Female      154181
3               Sunday              UK      25-34        Female      143924
4               Sunday           Italy      18-24          Male      120702
..                 ...             ...        ...           ...         ...
60            Saturday         Germany      35-44          Male        9808
61              Sunday           Italy      45-54        Female        7245
62            Saturday             USA      35-44          Male        5729
63              Sunday              UK      45-54          Male        1020
64              Sunday          Canada      25-34        Female         239

[65 rows x 5 columns]

In [165]:
weekday_thiller_views=weekday_thiller_views.groupby(["Peak Viewership Day","Viewer Location","Viewer Age","Viewer Gender"]).agg({"Viewership":"sum"}).reset_index()
weekday_thiller_views.sort_values(by=["Viewership"],ascending=[False]).reset_index(drop=True)
weekend_thiller_views["Viewership"].mean()

np.float64(65259.230769230766)

In [166]:
views_by_weekdays

  Peak Viewership Day  Viewership
0              Friday    13604412
1              Monday       74558
2            Saturday    18668685
3              Sunday    13525254
4            Thursday       59999
5             Tuesday     5239107
6           Wednesday        6133

In [167]:
weekend_thiller_views

   Peak Viewership Day Viewer Location Viewer Age Viewer Gender  Viewership
0             Saturday       Australia      18-24        Female       16804
1             Saturday       Australia      25-34        Female       83089
2             Saturday       Australia      25-34          Male      175206
3             Saturday       Australia      35-44        Female       67350
4             Saturday          Canada      18-24        Female       44898
..                 ...             ...        ...           ...         ...
60              Sunday              UK      45-54          Male        1020
61              Sunday             USA      18-24          Male       14667
62              Sunday             USA      35-44        Female       43584
63              Sunday             USA      35-44          Male       71926
64              Sunday             USA      45-54          Male       25552

[65 rows x 5 columns]

In [168]:
weekday_thiller_views=content_weekday_views.loc[content_weekday_views["Genre"]=="Thriller",:].reset_index(drop=True)
weekday_thiller_views.groupby(["Peak Viewership Day"]).agg({"Viewership":"sum"}).reset_index()
weekday_thiller_views.sort_values(by=["Viewership"],ascending=[False]).reset_index()
weekday_thiller_views["Viewership"].mean()

np.float64(54434.95238095238)

In [169]:
# Why did the viewership for "Thriller" genre spike on weekends?
thriller_data=content_weekend_views.loc[content_weekend_views["Genre"]=="Thriller",:]
views_by_weekend=thriller_data.groupby(by=["Peak Viewership Day","Genre"]).agg({"Viewership":"sum"}).reset_index()
views_by_weekend.sort_values(by=["Viewership"],ascending=[False]).reset_index(drop=True)

  Peak Viewership Day     Genre  Viewership
0            Saturday  Thriller     2578846
1              Sunday  Thriller     1663004

In [170]:
thriller_data=content_weekend_views.loc[content_weekend_views["Genre"]=="Thriller",:]
views_by_weekend=thriller_data.groupby(by=["Peak Viewership Day","Viewer Age"]).agg({"Viewership":"sum"}).reset_index()
views_by_weekend.sort_values(by=["Viewership"],ascending=[False]).reset_index(drop=True)

  Peak Viewership Day Viewer Age  Viewership
0            Saturday      35-44      872065
1            Saturday      25-34      717240
2            Saturday      18-24      588959
3              Sunday      25-34      476791
4              Sunday      45-54      453234
5            Saturday      45-54      400582
6              Sunday      35-44      378236
7              Sunday      18-24      354743

In [171]:
thriller_data=content_weekend_views.loc[content_weekend_views["Genre"]=="Thriller",:]
views_by_weekend=thriller_data.groupby(by=["Peak Viewership Day","Viewer Gender"]).agg({"Viewership":"sum"}).reset_index()
views_by_weekend.sort_values(by=["Viewership"],ascending=[False]).reset_index(drop=True)

  Peak Viewership Day Viewer Gender  Viewership
0            Saturday          Male     1299662
1            Saturday        Female     1279184
2              Sunday          Male      849069
3              Sunday        Female      813935

In [172]:
thriller_data=content_weekend_views.loc[content_weekend_views["Genre"]=="Thriller",:]
views_by_weekend=thriller_data.groupby(by=["Peak Viewership Day","Genre","Viewer Age","Viewer Gender"]).agg({"Viewership":"sum"}).reset_index()
views_by_weekend.sort_values(by=["Viewership"],ascending=[False]).reset_index(drop=True)

   Peak Viewership Day     Genre Viewer Age Viewer Gender  Viewership
0             Saturday  Thriller      35-44          Male      489234
1               Sunday  Thriller      45-54        Female      426662
2             Saturday  Thriller      35-44        Female      382831
3             Saturday  Thriller      25-34        Female      366011
4             Saturday  Thriller      25-34          Male      351229
5             Saturday  Thriller      18-24          Male      307025
6               Sunday  Thriller      35-44          Male      292442
7               Sunday  Thriller      25-34          Male      282657
8             Saturday  Thriller      18-24        Female      281934
9             Saturday  Thriller      45-54        Female      248408
10              Sunday  Thriller      18-24          Male      247398
11              Sunday  Thriller      25-34        Female      194134
12            Saturday  Thriller      45-54          Male      152174
13              Sunday  Thriller      18-24        Female      107345
14              Sunday  Thriller      35-44        Female       85794
15              Sunday  Thriller      45-54          Male       26572

In [173]:
content_releassed_weekend=content_df.loc[content_df["Day of the Week"].isin(["Sunday","Saturday"])].reset_index()
content_releassed_weekday=content_df.loc[content_df["Day of the Week"].isin(["Monday","Tuesday","Wednesday","Thursday","Friday"])].reset_index()

In [174]:
content_releassed_weekday_thiller=content_releassed_weekday.loc[content_releassed_weekday["Genre"]=="Thriller",:]
content_releassed_weekday_thiller["Viewership"].mean()

np.float64(53032.12643678161)

In [175]:
content_releassed_weekend_thiller=content_releassed_weekend.loc[content_releassed_weekend["Genre"]=="Thriller",:]
content_releassed_weekend_thiller["Viewership"].mean()

np.float64(47858.075)

In [176]:
# Why did Content A perform better than Content B even with similar ratings?
content_A["Viewership"].mean()

np.float64(54004.76377952756)

In [177]:
content_B["Viewership"].mean()

np.float64(51430.643356643355)

In [226]:
content_A["Comments"].mean()

np.float64(727.8818897637796)

In [225]:
content_B["Comments"].mean()

np.float64(698.7412587412588)

In [223]:
content_A["Likes"].mean()

np.float64(1606.1102362204724)

In [224]:
content_B["Likes"].mean()

np.float64(1478.6013986013986)

In [222]:
content_A["Shares"].mean()

np.float64(990.0157480314961)

In [221]:
content_B["Shares"].mean()

np.float64(974.5734265734266)

In [228]:
content_A["User Ratings"].mean()

np.float64(2.6606299212598428)

In [227]:
content_B["User Ratings"].mean()

np.float64(2.896503496503497)

In [178]:
content_A.groupby(by=["Day of the Week"]).agg({"Viewership":"mean"}).reset_index()

  Day of the Week    Viewership
0          Friday  53224.409091
1          Monday  58642.800000
2        Saturday  60132.307692
3          Sunday  47132.000000
4        Thursday  62678.687500
5         Tuesday  53208.611111
6       Wednesday  46326.000000

In [179]:
# content_A.groupby(by=["Seasonality"]).agg({"Seasonality":"count"}).reset_index()
content_A["Seasonality"].value_counts()

Seasonality
Spring    40
Winter    36
Fall      33
Summer    18
Name: count, dtype: int64

In [180]:
content_B.groupby(by=["Day of the Week"]).agg({"Viewership":"mean"}).reset_index()

  Day of the Week    Viewership
0          Friday  59299.894737
1          Monday  47913.555556
2        Saturday  48444.083333
3          Sunday  54868.000000
4        Thursday  51606.818182
5         Tuesday  52652.368421
6       Wednesday  43458.562500

In [181]:
content_B["Seasonality"].value_counts()

Seasonality
Winter    43
Spring    37
Summer    35
Fall      28
Name: count, dtype: int64

In [182]:
content_A_views=content_A.groupby(by=["Viewer Location"]).agg({"Viewership":"mean"}).reset_index()
content_A_views.sort_values(by=["Viewership"],ascending=False)

  Viewer Location    Viewership
3         Germany  64179.333333
4           India  60799.375000
5           Italy  59252.812500
6              UK  56872.043478
0       Australia  51966.842105
1          Canada  51897.818182
7             USA  51560.714286
2          France  36216.562500

In [183]:
content_A_views=content_A.groupby(by=["Viewer Gender"]).agg({"Viewership":"mean"}).reset_index()
content_A_views.sort_values(by=["Viewership"],ascending=False)

  Viewer Gender    Viewership
1          Male  54521.666667
0        Female  53389.827586

In [184]:
content_B_views=content_B.groupby(by=["Viewer Location"]).agg({"Viewership":"mean"}).reset_index()
content_B_views.sort_values(by=["Viewership"],ascending=False)

  Viewer Location    Viewership
4           India  62532.000000
2          France  56680.533333
6              UK  54172.411765
1          Canada  53455.000000
0       Australia  49360.200000
3         Germany  48312.833333
5           Italy  42679.000000
7             USA  40602.333333

In [185]:
content_B_views=content_B.groupby(by=["Viewer Gender"]).agg({"Viewership":"mean"}).reset_index()
content_B_views.sort_values(by=["Viewership"],ascending=False)

  Viewer Gender    Viewership
1          Male  52489.652778
0        Female  50356.718310

In [186]:
content_A.groupby(by=["Viewer Age"]).agg({"Viewership":"mean"}).reset_index()

  Viewer Age    Viewership
0      18-24  58572.604651
1      25-34  49531.485714
2      35-44  51598.888889
3      45-54  55145.954545

In [187]:
content_B.groupby(by=["Viewer Age"]).agg({"Viewership":"mean"}).reset_index()

  Viewer Age    Viewership
0      18-24  53905.710526
1      25-34  55104.645161
2      35-44  49548.708333
3      45-54  46907.038462

In [188]:
#Is there a relationship between content duration and completion rate?
content_df_cont['Duration (mins)'].corr(content_df_cont['Average Watch Time (mins)'])

np.float64(0.3477985871112226)

In [189]:
content_df_cont.corr()['Average Watch Time (mins)']

Content ID                      -0.052560
Duration (mins)                  0.347799
Viewership                       0.019127
Average Watch Time (mins)        1.000000
Likes                            0.018299
Shares                          -0.017028
Comments                         0.000782
User Ratings                     0.006706
Subscription Data               -0.078344
Hour                             0.025973
Minute                          -0.053187
Hour.1_peak_viewership_time     -0.021667
Minute.1_peak_viewership_time   -0.015503
Name: Average Watch Time (mins), dtype: float64

In [190]:
# Does promotional effort correlate with viewership or engagement?
content_new_df["Viewership"].corr(content_new_df['Promotion Data_Email Campaign'])

np.float64(0.021099938112411676)

In [250]:
content_new_df.corr()["Shares"].to_dict()

{'Content ID': -0.009218825128815486,
 'Duration (mins)': -0.009709135210228405,
 'Viewership': 0.005737222159677449,
 'Average Watch Time (mins)': -0.01702809336228473,
 'Likes': -0.07993836115785077,
 'Shares': 1.0,
 'Comments': -0.00698558825717815,
 'User Ratings': -0.022792529525207203,
 'Subscription Data': 0.03263821312810245,
 'Hour': -0.0009424638522834706,
 'Minute': 0.0032575031437410244,
 'Hour.1_peak_viewership_time': -0.007924387135996544,
 'Minute.1_peak_viewership_time': 0.01276385179608798,
 'Content Type_Movie': 0.033614387326339805,
 'Content Type_Series': -0.002470314285715748,
 'Genre_Comedy': 0.011892418678518583,
 'Genre_Drama': 0.014026917770373659,
 'Genre_Fantasy': -0.04526826738607657,
 'Genre_History': 0.017743928524314,
 'Genre_Nature': -0.012151139620223446,
 'Genre_Romance': 0.022272071349209662,
 'Genre_Sci-Fi': -0.018478993820732363,
 'Genre_Thriller': 0.02007473207315939,
 'Day of the Week_Monday': 0.06389899243912879,
 'Day of the Week_Saturday': 0.0444197860344868,
 'Day of the Week_Sunday': -0.07796245245746089,
 'Day of the Week_Thursday': 0.0026557343709222767,
 'Day of the Week_Tuesday': -0.004414342245697951,
 'Day of the Week_Wednesday': 0.006766679523701218,
 'Peak Viewership Day_Monday': 0.04410108629536841,
 'Peak Viewership Day_Saturday': 0.005166146007579207,
 'Peak Viewership Day_Sunday': 0.00023387101314866008,
 'Peak Viewership Day_Thursday': -0.014816818437570945,
 'Peak Viewership Day_Tuesday': 0.0472373103851772,
 'Peak Viewership Day_Wednesday': -0.03262287652229468,
 'Viewer Age_25-34': -0.015308947418307395,
 'Viewer Age_35-44': 0.05923308036255792,
 'Viewer Age_45-54': -0.02906753116642212,
 'Viewer Gender_Male': 0.0058661759841367065,
 'Viewer Location_Canada': 0.02957979725775308,
 'Viewer Location_France': -0.014527938028347969,
 'Viewer Location_Germany': -0.004334103382594019,
 'Viewer Location_India': -0.007676344567609597,
 'Viewer Location_Italy': 0.0019339690208879643,
 'Viewer Location_UK': 0.03055174334772472,
 'Viewer Location_USA': -0.0070522608411624985,
 'Seasonality_Spring': 0.0007969544520899706,
 'Seasonality_Summer': -0.045831300226138766,
 'Seasonality_Winter': -0.045699855440401074,
 'Content Popularity_Low': 0.012890999816543132,
 'Content Popularity_Medium': -0.020089286008745967,
 'Competitor Content_Similar Doc C': 0.03448877252609128,
 'Competitor Content_Similar History G': 0.022011425848852385,
 'Competitor Content_Similar Movie A': 0.011101611247171642,
 'Competitor Content_Similar Romance F': -0.0037823567513139743,
 'Competitor Content_Similar Sci-Fi E': -0.10070566772220811,
 'Competitor Content_Similar Series B': 0.0010330664900864777,
 'Competitor Content_Similar Thriller H': 0.03897639004979008,
 'Promotion Data_Email Campaign': 0.03447963907544434,
 'Promotion Data_Online Ads': 0.007968644220378218,
 'Promotion Data_Print Media': -0.032560755147195884,
 'Promotion Data_Social Media': -0.027033820630594063,
 'Promotion Data_TV Ads': 0.016402750809861734}

In [251]:
content_new_df.corr()["Likes"].to_dict()

{'Content ID': -0.00314207300177341,
 'Duration (mins)': 0.018168038691366274,
 'Viewership': 0.028812432794165926,
 'Average Watch Time (mins)': 0.0182988174379648,
 'Likes': 1.0,
 'Shares': -0.07993836115785077,
 'Comments': 0.029236632426971765,
 'User Ratings': -0.002483924896805528,
 'Subscription Data': 0.035868724797419475,
 'Hour': -0.011413567322785189,
 'Minute': 0.03918649918874543,
 'Hour.1_peak_viewership_time': -0.0040405665581131935,
 'Minute.1_peak_viewership_time': -0.045306143883520035,
 'Content Type_Movie': 0.01290165321643673,
 'Content Type_Series': 0.01413565599858882,
 'Genre_Comedy': -0.050707104813666394,
 'Genre_Drama': -0.03091196084856294,
 'Genre_Fantasy': -0.006502200144044002,
 'Genre_History': -0.011881683774829444,
 'Genre_Nature': 0.012242901043780964,
 'Genre_Romance': -0.01113365426942326,
 'Genre_Sci-Fi': 0.02850448506358884,
 'Genre_Thriller': 0.05791844018160049,
 'Day of the Week_Monday': -0.005394095003684081,
 'Day of the Week_Saturday': -0.021373712144493937,
 'Day of the Week_Sunday': 0.031531142914229586,
 'Day of the Week_Thursday': -0.04694526682702689,
 'Day of the Week_Tuesday': 0.003139625769186228,
 'Day of the Week_Wednesday': 0.007783697680250626,
 'Peak Viewership Day_Monday': -0.021009454945604945,
 'Peak Viewership Day_Saturday': -0.022243753249819975,
 'Peak Viewership Day_Sunday': 0.020971298731109464,
 'Peak Viewership Day_Thursday': 0.052971914304809464,
 'Peak Viewership Day_Tuesday': 0.025734163625390064,
 'Peak Viewership Day_Wednesday': 0.04211653663755738,
 'Viewer Age_25-34': -0.01895341885669497,
 'Viewer Age_35-44': -0.009635116316890579,
 'Viewer Age_45-54': 0.028433377085057145,
 'Viewer Gender_Male': 0.0021702093745845164,
 'Viewer Location_Canada': 0.01156280023075919,
 'Viewer Location_France': 0.02238626598647403,
 'Viewer Location_Germany': -0.05086215922314884,
 'Viewer Location_India': 0.004074823290803275,
 'Viewer Location_Italy': -0.024829591934471155,
 'Viewer Location_UK': 0.009184646629137734,
 'Viewer Location_USA': 0.026470689466121095,
 'Seasonality_Spring': 0.03935282097788242,
 'Seasonality_Summer': 0.03114537668591048,
 'Seasonality_Winter': 0.009736982950767721,
 'Content Popularity_Low': -0.003020035024183726,
 'Content Popularity_Medium': -0.004652592601473355,
 'Competitor Content_Similar Doc C': -0.01471102594006711,
 'Competitor Content_Similar History G': 0.009301618874541413,
 'Competitor Content_Similar Movie A': 0.04694078470248477,
 'Competitor Content_Similar Romance F': 0.0035708956555878454,
 'Competitor Content_Similar Sci-Fi E': -0.014950286571178813,
 'Competitor Content_Similar Series B': -0.008706936531111601,
 'Competitor Content_Similar Thriller H': -0.00986336609159684,
 'Promotion Data_Email Campaign': -0.06214206077822754,
 'Promotion Data_Online Ads': 0.019992955316188738,
 'Promotion Data_Print Media': 0.04058548516273597,
 'Promotion Data_Social Media': -0.003823540854413864,
 'Promotion Data_TV Ads': -0.000506939076081229}

In [252]:
content_new_df.corr()["Comments"].to_dict()

{'Content ID': 0.05863472767383917,
 'Duration (mins)': -0.011372525463113254,
 'Viewership': 0.022434639800781708,
 'Average Watch Time (mins)': 0.0007820782388793304,
 'Likes': 0.029236632426971765,
 'Shares': -0.00698558825717815,
 'Comments': 1.0,
 'User Ratings': -0.07657354156799169,
 'Subscription Data': -0.03493126651988078,
 'Hour': 0.015947531792390633,
 'Minute': -0.07737055822811419,
 'Hour.1_peak_viewership_time': -0.02580113477120376,
 'Minute.1_peak_viewership_time': 0.041973793396459444,
 'Content Type_Movie': 0.018121820544157192,
 'Content Type_Series': -0.00997844265843268,
 'Genre_Comedy': 0.012870488872669974,
 'Genre_Drama': -0.053468222374395434,
 'Genre_Fantasy': -0.005236779832677215,
 'Genre_History': 0.022162669552694702,
 'Genre_Nature': 0.03784312977336561,
 'Genre_Romance': -0.018759304632493506,
 'Genre_Sci-Fi': -0.0032279501948145888,
 'Genre_Thriller': 0.04055094794254776,
 'Day of the Week_Monday': -0.002386601610001554,
 'Day of the Week_Saturday': -0.014399907232990413,
 'Day of the Week_Sunday': -0.017853801417357096,
 'Day of the Week_Thursday': -0.03632371605445218,
 'Day of the Week_Tuesday': 0.02194284322741804,
 'Day of the Week_Wednesday': 0.02664029601699377,
 'Peak Viewership Day_Monday': -0.013485283090233084,
 'Peak Viewership Day_Saturday': 0.014071075704683463,
 'Peak Viewership Day_Sunday': -0.030557769529060353,
 'Peak Viewership Day_Thursday': -0.004882963400105895,
 'Peak Viewership Day_Tuesday': 0.028371769237545228,
 'Peak Viewership Day_Wednesday': -0.042876542031500924,
 'Viewer Age_25-34': 0.002323175551821642,
 'Viewer Age_35-44': 0.005075138172211352,
 'Viewer Age_45-54': -0.0009963881150540075,
 'Viewer Gender_Male': 0.014834348851322331,
 'Viewer Location_Canada': 0.035507627045205145,
 'Viewer Location_France': 0.03941482096476584,
 'Viewer Location_Germany': 0.016774870873735262,
 'Viewer Location_India': -0.056997723616583874,
 'Viewer Location_Italy': 0.008516796230731349,
 'Viewer Location_UK': -0.00513841237688618,
 'Viewer Location_USA': 0.0017504107292888736,
 'Seasonality_Spring': -0.009998683210996086,
 'Seasonality_Summer': 0.012008447744890424,
 'Seasonality_Winter': -0.0007675679182697246,
 'Content Popularity_Low': -0.05361361093881164,
 'Content Popularity_Medium': 0.012086811880382416,
 'Competitor Content_Similar Doc C': -0.006936838082623274,
 'Competitor Content_Similar History G': 0.0474053382140066,
 'Competitor Content_Similar Movie A': -0.01316524388813877,
 'Competitor Content_Similar Romance F': -0.03984850741115774,
 'Competitor Content_Similar Sci-Fi E': 0.06528706679454828,
 'Competitor Content_Similar Series B': -0.04107054991837735,
 'Competitor Content_Similar Thriller H': 0.0062657360244210685,
 'Promotion Data_Email Campaign': -0.04482796030816276,
 'Promotion Data_Online Ads': 0.03669972003426725,
 'Promotion Data_Print Media': 0.04187936676085513,
 'Promotion Data_Social Media': 0.012663263445468276,
 'Promotion Data_TV Ads': -0.039798673790654014}

In [248]:
content_new_df.corr()["Viewership"].to_dict()

{'Content ID': -0.024123734390442318,
 'Duration (mins)': 0.018129304811079452,
 'Viewership': 1.0,
 'Average Watch Time (mins)': 0.019127211571507523,
 'Likes': 0.028812432794165926,
 'Shares': 0.005737222159677449,
 'Comments': 0.022434639800781708,
 'User Ratings': -0.03519711455455529,
 'Subscription Data': -0.01616408000756434,
 'Hour': -0.021520487273631105,
 'Minute': -0.006527084097373425,
 'Hour.1_peak_viewership_time': -0.01112817402600305,
 'Minute.1_peak_viewership_time': -9.353004966385485e-05,
 'Content Type_Movie': 0.015397070506285592,
 'Content Type_Series': 0.014178512698243287,
 'Genre_Comedy': 0.039929592427098454,
 'Genre_Drama': -0.002043596284345476,
 'Genre_Fantasy': -0.03887760057902384,
 'Genre_History': -0.018783660676422297,
 'Genre_Nature': 0.003733417744946578,
 'Genre_Romance': -0.02600720286279158,
 'Genre_Sci-Fi': 0.014644274935115458,
 'Genre_Thriller': 0.0029981116423671386,
 'Day of the Week_Monday': -0.028677444335513093,
 'Day of the Week_Saturday': 0.0001359369890824146,
 'Day of the Week_Sunday': 0.013017896388324617,
 'Day of the Week_Thursday': 0.012190173407059024,
 'Day of the Week_Tuesday': 0.017821269147539096,
 'Day of the Week_Wednesday': -0.00883529945480883,
 'Peak Viewership Day_Monday': 0.02591639015019087,
 'Peak Viewership Day_Saturday': -0.004547048856166908,
 'Peak Viewership Day_Sunday': 0.009288761870445434,
 'Peak Viewership Day_Thursday': 0.00977784811850349,
 'Peak Viewership Day_Tuesday': -0.021143896282658337,
 'Peak Viewership Day_Wednesday': -0.049932207866032974,
 'Viewer Age_25-34': 0.02248357539322332,
 'Viewer Age_35-44': -0.0392763172344087,
 'Viewer Age_45-54': -0.008970151843782262,
 'Viewer Gender_Male': 0.04370409500853457,
 'Viewer Location_Canada': 0.007522722877433618,
 'Viewer Location_France': -0.05359218509336157,
 'Viewer Location_Germany': -0.0016301998139996031,
 'Viewer Location_India': 0.035879282663003595,
 'Viewer Location_Italy': 0.04188990170736779,
 'Viewer Location_UK': 0.051633476932198795,
 'Viewer Location_USA': -0.0604027820880532,
 'Seasonality_Spring': 0.0070447897815690405,
 'Seasonality_Summer': 0.007995677131533334,
 'Seasonality_Winter': -0.022092216123499694,
 'Content Popularity_Low': 0.028061045312065852,
 'Content Popularity_Medium': -0.040992312744171956,
 'Competitor Content_Similar Doc C': 0.000550130350754075,
 'Competitor Content_Similar History G': 0.0022193927914490874,
 'Competitor Content_Similar Movie A': 0.037772611637208214,
 'Competitor Content_Similar Romance F': 0.030527730933530544,
 'Competitor Content_Similar Sci-Fi E': -0.032603778982890005,
 'Competitor Content_Similar Series B': 0.003613653434305008,
 'Competitor Content_Similar Thriller H': 3.269546136469368e-05,
 'Promotion Data_Email Campaign': 0.021099938112411742,
 'Promotion Data_Online Ads': -0.04086614963551609,
 'Promotion Data_Print Media': 0.06638956693840627,
 'Promotion Data_Social Media': -0.01774939034519224,
 'Promotion Data_TV Ads': -0.035282272172442744}

In [195]:
#Are poor-performing contents linked to certain times or days?
content_wise_views=content_df.sort_values(by=["Viewership"],ascending=[True]).reset_index(drop=True)
content_released_count_by_day=content_wise_views.groupby(by=["Peak Viewership Day"]).agg({"Peak Viewership Day":"count"})
content_wise_views["Peak Viewership Day"].value_counts()

Peak Viewership Day
Saturday     366
Friday       263
Sunday       262
Tuesday      106
Wednesday      1
Thursday       1
Monday         1
Name: count, dtype: int64

In [262]:
views_by_week=content_df.groupby(by=["Peak Viewership Day","viewership_bins"]).agg(count_bins=("viewership_bins","count")).reset_index()
views_by_week.sort_values(by=["count_bins","viewership_bins"],ascending=[False,True]).reset_index(drop=True)

   Peak Viewership Day  viewership_bins  count_bins
0             Saturday                2          84
1             Saturday                4          77
2             Saturday                5          72
3             Saturday                3          69
4             Saturday                1          64
5               Friday                2          64
6               Sunday                3          61
7               Sunday                5          59
8               Sunday                2          55
9               Friday                4          55
10              Friday                5          55
11              Friday                3          49
12              Sunday                4          46
13              Sunday                1          41
14              Friday                1          40
15             Tuesday                4          33
16             Tuesday                1          27
17             Tuesday                5          18
18             Tuesday                2          15
19             Tuesday                3          13
20           Wednesday                1           1
21            Thursday                3           1
22              Monday                4           1

In [263]:
shares_by_week=content_df.groupby(by=["Peak Viewership Day","Shares_bins"]).agg(count_bins=("Shares_bins","count")).reset_index()
shares_by_week.sort_values(by=["count_bins","Shares_bins"],ascending=[False,True]).reset_index(drop=True)

   Peak Viewership Day  Shares_bins  count_bins
0             Saturday            1          79
1             Saturday            2          77
2             Saturday            5          73
3             Saturday            3          71
4             Saturday            4          66
5               Friday            2          65
6               Sunday            2          60
7               Friday            1          57
8               Sunday            1          56
9               Sunday            5          53
10              Friday            3          48
11              Sunday            3          48
12              Friday            5          47
13              Friday            4          46
14              Sunday            4          45
15             Tuesday            5          27
16             Tuesday            1          20
17             Tuesday            2          20
18             Tuesday            4          20
19             Tuesday            3          19
20           Wednesday            1           1
21            Thursday            2           1
22              Monday            5           1

In [264]:
Comments_by_week=content_df.groupby(by=["Peak Viewership Day","Comments_bins"]).agg(count_bins=("Comments_bins","count")).reset_index()
Comments_by_week.sort_values(by=["count_bins","Comments_bins"],ascending=[False,True]).reset_index(drop=True)

   Peak Viewership Day  Comments_bins  count_bins
0             Saturday              5          83
1             Saturday              1          79
2             Saturday              2          72
3               Sunday              2          66
4             Saturday              3          66
5             Saturday              4          66
6               Sunday              1          60
7               Friday              4          58
8               Sunday              5          58
9               Friday              3          57
10              Friday              1          53
11              Friday              2          49
12              Friday              5          46
13              Sunday              4          42
14              Sunday              3          36
15             Tuesday              4          30
16             Tuesday              2          26
17             Tuesday              5          19
18             Tuesday              1          17
19             Tuesday              3          14
20           Wednesday              1           1
21              Monday              2           1
22            Thursday              3           1

In [265]:
Likes_by_week=content_df.groupby(by=["Peak Viewership Day","Likes_bins"]).agg(count_bins=("Likes_bins","count")).reset_index()
Likes_by_week.sort_values(by=["count_bins","Likes_bins"],ascending=[False,True]).reset_index(drop=True)

   Peak Viewership Day  Likes_bins  count_bins
0             Saturday           2          78
1             Saturday           5          78
2             Saturday           1          75
3             Saturday           3          70
4             Saturday           4          65
5               Friday           3          62
6               Sunday           1          61
7               Sunday           5          59
8               Friday           1          58
9               Friday           4          54
10              Sunday           4          54
11              Sunday           3          47
12              Friday           5          46
13              Friday           2          43
14              Sunday           2          41
15             Tuesday           5          27
16             Tuesday           1          24
17             Tuesday           3          23
18             Tuesday           4          18
19             Tuesday           2          14
20              Monday           2           1
21            Thursday           5           1
22           Wednesday           5           1

In [200]:
content_df.groupby(by=["Seasonality","viewership_bins"]).agg({"viewership_bins":"count"})

                             viewership_bins
Seasonality viewership_bins
Fall        1                             42
            2                             51
            3                             45
            4                             39
            5                             56
Spring      1                             43
            2                             68
            3                             44
            4                             58
            5                             58
Summer      1                             43
            2                             44
            3                             53
            4                             57
            5                             45
Winter      1                             45
            2                             55
            3                             51
            4                             58
            5                             45

In [201]:
views_by_seasonality=content_df.groupby(by=["Seasonality","viewership_bins"]).agg({"Viewership":"sum"}).reset_index()
views_by_seasonality.sort_values(by=["Viewership","viewership_bins"],ascending=[True,True])

   Seasonality  viewership_bins  Viewership
0         Fall                1      407186
15      Winter                1      428445
10      Summer                1      457412
5       Spring                1      464272
11      Summer                2     1286644
1         Fall                2     1525748
16      Winter                2     1595712
6       Spring                2     2051226
7       Spring                3     2202279
2         Fall                3     2252271
17      Winter                3     2591277
12      Summer                3     2642242
3         Fall                4     2779885
13      Summer                4     3977394
8       Spring                4     4009659
19      Winter                5     4052011
18      Winter                4     4057325
14      Summer                5     4119162
4         Fall                5     5046784
9       Spring                5     5231214

In [202]:
hourly_views=content_df.groupby(by=["Hour.1_peak_viewership_time"]).agg({"Viewership":"sum"}).reset_index()
hourly_views.sort_values(by=["Viewership"],ascending=[False]).reset_index(drop=True)

    Hour.1_peak_viewership_time  Viewership
0                             2     3702579
1                             3     2893604
2                             0     2523669
3                             8     2468825
4                            21     2378107
5                             1     2335709
6                            18     2242158
7                            16     2186174
8                            13     2180380
9                            10     2159700
10                            5     2116904
11                           17     2102786
12                           23     2088367
13                           12     2060088
14                           15     2009578
15                            7     1968658
16                           22     1964982
17                           11     1901742
18                           14     1895390
19                            4     1868027
20                           19     1686848
21                            9     1626433
22                            6     1431702
23                           20     1385738

In [203]:
content_wise_views["Peak Viewership Day"].value_counts()

Peak Viewership Day
Saturday     366
Friday       263
Sunday       262
Tuesday      106
Wednesday      1
Thursday       1
Monday         1
Name: count, dtype: int64

In [204]:
#Is content released on weekends performing better than weekdays?
performance_by_day=content_df.groupby(by=["Day of the Week"]).agg({"Shares":"sum",
                                                    "Comments":"sum",
                                                    "Likes":"sum",
                                                    "Viewership":"sum"}).reset_index()
performance_by_day.sort_values(by=["Viewership","Shares","Comments","Likes"],ascending=[False,False,False,False])

  Day of the Week  Shares  Comments   Likes  Viewership
3          Sunday  138159    115274  248273     8273195
6       Wednesday  157138    123209  242108     8096054
0          Friday  145196    119118  241650     7950097
1          Monday  155183    108123  216942     7182988
2        Saturday  145190    101831  203090     7166287
5         Tuesday  115939     92321  180592     6306671
4        Thursday  116299     83240  164770     6202856

In [205]:
#views
views_by_days=content_df.groupby(by=["Day of the Week"]).agg({"Viewership":"sum"}).reset_index()
views_by_weekdays=views_by_days.loc[views_by_days["Day of the Week"].isin(["Friday","Monday","Thursday","Tuesday","Wednesday"]),:]
views_by_weekdays["Viewership"].mean()

np.float64(7147733.2)

In [206]:
#views
views_by_days=content_df.groupby(by=["Day of the Week"]).agg({"Viewership":"sum"}).reset_index()
views_by_weekends=views_by_days.loc[views_by_days["Day of the Week"].isin(["Saturday","Sunday"]),:]
views_by_weekends["Viewership"].mean()

np.float64(7719741.0)

In [207]:
#shares
views_by_days=content_df.groupby(by=["Day of the Week"]).agg({"Shares":"sum"}).reset_index()
views_by_weekdays=views_by_days.loc[views_by_days["Day of the Week"].isin(["Friday","Monday","Thursday","Tuesday","Wednesday"]),:]
views_by_weekdays["Shares"].mean()

np.float64(137951.0)

In [208]:
#shares
views_by_days=content_df.groupby(by=["Day of the Week"]).agg({"Shares":"sum"}).reset_index()
views_by_weekends=views_by_days.loc[views_by_days["Day of the Week"].isin(["Saturday","Sunday"]),:]
views_by_weekends["Shares"].mean()

np.float64(141674.5)

In [209]:
#Likes
views_by_days=content_df.groupby(by=["Day of the Week"]).agg({"Likes":"sum"}).reset_index()
views_by_weekdays=views_by_days.loc[views_by_days["Day of the Week"].isin(["Friday","Monday","Thursday","Tuesday","Wednesday"]),:]
views_by_weekdays["Likes"].mean()

np.float64(209212.4)

In [210]:
#Likes
views_by_days=content_df.groupby(by=["Day of the Week"]).agg({"Likes":"sum"}).reset_index()
views_by_weekdays=views_by_days.loc[views_by_days["Day of the Week"].isin(["Saturday","Sunday"]),:]
views_by_weekdays["Likes"].mean()

np.float64(225681.5)

In [211]:
#Comments
views_by_days=content_df.groupby(by=["Day of the Week"]).agg({"Comments":"sum"}).reset_index()
views_by_weekdays=views_by_days.loc[views_by_days["Day of the Week"].isin(["Friday","Monday","Thursday","Tuesday","Wednesday"]),:]
views_by_weekdays["Comments"].mean()

np.float64(105202.2)

In [212]:
#Comments
views_by_days=content_df.groupby(by=["Day of the Week"]).agg({"Comments":"sum"}).reset_index()
views_by_weekdays=views_by_days.loc[views_by_days["Day of the Week"].isin(["Saturday","Sunday"]),:]
views_by_weekdays["Comments"].mean()

np.float64(108552.5)

In [213]:
content_by_day__gender=content_df.groupby(by=["Day of the Week","Viewer Gender"]).agg({"Shares":"sum",
                                                    "Comments":"sum",
                                                    "Likes":"sum",
                                                    "Viewership":"sum"}).reset_index()
content_by_day__gender.sort_values(by=["Shares","Comments","Likes","Viewership"],ascending=[False,False,False,False]).reset_index(drop=True)

   Day of the Week Viewer Gender  Shares  Comments   Likes  Viewership
0        Wednesday        Female   96516     70935  142924     4558833
1         Saturday        Female   85061     58511  125713     4187377
2           Friday          Male   84606     68739  142540     4928961
3           Monday        Female   78866     50819  114989     3712739
4           Monday          Male   76317     57304  101953     3470249
5           Sunday        Female   70317     64610  121373     4300528
6           Sunday          Male   67842     50664  126900     3972667
7          Tuesday          Male   66077     49659   97577     3438661
8         Thursday        Female   62126     44490   89082     3289585
9        Wednesday          Male   60622     52274   99184     3537221
10          Friday        Female   60590     50379   99110     3021136
11        Saturday          Male   60129     43320   77377     2978910
12        Thursday          Male   54173     38750   75688     2913271
13         Tuesday        Female   49862     42662   83015     2868010

In [214]:
content_by_gender=content_df.groupby(by=["Viewer Gender"]).agg({"Shares":"sum",
                                                    "Comments":"sum",
                                                    "Likes":"sum",
                                                    "Viewership":"sum"}).reset_index()
content_by_gender.sort_values(by=["Viewership","Comments","Likes","Viewership"],ascending=[False,False,False,False])

  Viewer Gender  Shares  Comments   Likes  Viewership
0        Female  503338    382406  776206    25938208
1          Male  469766    360710  721219    25239940

In [215]:
views_by_location=content_df.groupby(by=["Viewer Location"]).agg({"Shares":"sum",
                                                    "Comments":"sum",
                                                    "Likes":"sum",
                                                    "Viewership":"sum"}).reset_index()
views_by_location.sort_values(by=["Viewership","Comments","Likes","Viewership"],ascending=[False,False,False,False])

  Viewer Location  Shares  Comments   Likes  Viewership
6              UK  136443     98805  203418     7359899
1          Canada  135259    104156  202625     6879605
5           Italy  122984     94880  181399     6845213
4           India  116291     81713  182362     6526532
0       Australia  118620     89305  192078     6316244
3         Germany  114984     90828  163650     6075134
7             USA  118346     91657  191861     5728681
2          France  110177     91772  180032     5446840

In [216]:
# Why did engagement drop in a specific region or age group?
views_by_location=content_df.groupby(by=["Viewer Location"]).agg({"Shares":"sum",
                                                    "Comments":"sum",
                                                    "Likes":"sum",
                                                    "Viewership":"sum"}).reset_index()
views_by_location.sort_values(by=["Viewership","Comments","Likes","Viewership"],ascending=[False,False,False,False])

  Viewer Location  Shares  Comments   Likes  Viewership
6              UK  136443     98805  203418     7359899
1          Canada  135259    104156  202625     6879605
5           Italy  122984     94880  181399     6845213
4           India  116291     81713  182362     6526532
0       Australia  118620     89305  192078     6316244
3         Germany  114984     90828  163650     6075134
7             USA  118346     91657  191861     5728681
2          France  110177     91772  180032     5446840

In [217]:
views_by_location=content_df.groupby(by=["Viewer Gender"]).agg({"Shares":"sum",
                                                    "Comments":"sum",
                                                    "Likes":"sum",
                                                    "Viewership":"sum"}).reset_index()
views_by_location.sort_values(by=["Viewership","Comments","Likes","Viewership"],ascending=[False,False,False,False])

  Viewer Gender  Shares  Comments   Likes  Viewership
0        Female  503338    382406  776206    25938208
1          Male  469766    360710  721219    25239940

In [218]:
views_by_location=content_df.groupby(by=["Viewer Age"]).agg({"Shares":"sum",
                                                    "Comments":"sum",
                                                    "Likes":"sum",
                                                    "Viewership":"sum"}).reset_index()
views_by_location.sort_values(by=["Viewership","Comments","Likes","Viewership"],ascending=[False,False,False,False])

  Viewer Age  Shares  Comments   Likes  Viewership
0      18-24  246028    189752  384843    13483440
2      35-44  269095    194937  387091    12865165
3      45-54  233073    183360  380693    12530587
1      25-34  224908    175067  344798    12298956